name = "unraidwatch-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "unraidwatch"
database_id = "122630f7-fbd9-484a-a0c6-c7364a93e189"
migrations_dir = "../migrations"

[[kv_namespaces]]
binding = "SESSIONS"
id = "9c3d691b68ca4441b58f069e7b4d645d"

[vars]
ENVIRONMENT = "production"
APP_URL = "https://unraidwatch.pages.dev"

[triggers]
crons = [
  "0 * * * *",
  "0 7 * * *"
]
